build.gradle

See https://www.osgeo.org/foundation-news/new-osgeo-repo/

change to osgeo repo

---

xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/app/FilterEncoderSqlNewNewImpl.java

additional special treatment for unbounded intervals

---

xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/CqlImpl.java
xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/Geometry.java

closes https://github.com/interactive-instruments/ldproxy/issues/434

inject filter-crs value

---

xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/app/ExtentReaderSql.java
xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/app/FeatureStoreQueryGeneratorSql.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureStoreQueryGenerator.java

Both in the spatial and temporal extent queries.

add provider type filter in extent queries

---

xtraplatform-geometries/src/main/java/de/ii/xtraplatform/geometries/domain/CoordinatesTransformer.java

closes https://github.com/interactive-instruments/ldproxy/issues/489

transform coordinates, if precision is provided

---

xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/ValueTransformerChain.java

closes https://github.com/interactive-instruments/ldproxy/issues/666

Abort value transformation chains, if the value has been transformed to null

---

xtraplatform-features-gml/src/main/java/de/ii/xtraplatform/features/gml/app/FilterEncoderWfs.java

closes https://github.com/interactive-instruments/ldproxy/issues/698

WFS: support CQL2 filter in Feature query

---

xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureSchema.java

See https://github.com/interactive-instruments/ldproxy/issues/681

Add support for 'unit' in FeatureSchema

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FeatureProviderSql.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/GeometryDecoderWkt.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/AbstractFeatureProvider.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureTokenTransformerSorting.java

I tested it with `gebaeude`, for these cases it works as expected.

rearrange decoded sql according to feature schema

---

xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureTokenTransformerSchemaMappings.java

apply schema transformation to geometries

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FeatureProviderSqlFactory.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureSchema.java

needed for proper (de)serialization in ldproxy-cfg

improve constant normalization

---

xtraplatform-features-gml/build.gradle
xtraplatform-features-gml/src/main/java/de/ii/xtraplatform/features/gml/app/FeatureProviderWfs.java
xtraplatform-features-gml/src/main/java/de/ii/xtraplatform/features/gml/app/FeatureTokenDecoderGml.java
xtraplatform-features-gml/src/test/groovy/de/ii/xtraplatform/features/gml/app/FeatureTokenDecoderGmlSpec.groovy
xtraplatform-features-gml/src/test/resources/simple_polygon_inner.xml
xtraplatform-features/src/testFixtures/groovy/de/ii/xtraplatform/features/domain/FeatureTokenFixtures.groovy

Closes interactive-instruments/ldproxy#716.

fix gml polygon inner ring

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/GeometryDecoderWkt.java

Closes https://github.com/interactive-instruments/ldproxy/issues/747

Fix MultiPoint WKT encoding

---

xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/CqlTypeChecker.java

ensure that name comparison is case-insensitive (in upper case)

fix type compatibility check

---

xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/TileWalkerImpl.java

If a feature type has no features, the spatial extent of the collection is empty. In this case the bounding box of the tile matrix set was used as a fallback for the spatial extent, which for WebMercatorQuad results in seeding the whole world. Instead the layer / collection has to be skipped.

Only seed layers with features

---

xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/CqlVisitorMapTemporalOperators.java

Closes https://github.com/interactive-instruments/ldproxy/issues/863

fix T_Intersects with INTERVAL(start,end) and instant literal

---

xtraplatform-feature-changes-sql/src/main/java/de/ii/xtraplatform/feature/changes/sql/app/FeatureChangesPgListener.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/PropertyTransformations.java
xtraplatform-routes-sql/src/main/java/de/ii/xtraplatform/routes/sql/app/RoutesQueriesSql.java
xtraplatform-routes-sql/src/main/java/de/ii/xtraplatform/routes/sql/domain/RoutesConfiguration.java

Plus additional changes to align with ldproxy documentation updates

Add documentation of the routing extension

---

xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTransformerDateFormat.java

Closes https://github.com/interactive-instruments/ldproxy/issues/920

Fix detection of time elements in dateFormat transformation

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/infra/db/SqlRowVals.java

Fixes interactive-instruments/ldproxy#952.

fix sortKey null comparison

---

xtraplatform-features-gml/src/main/java/de/ii/xtraplatform/features/gml/app/FeatureProviderWfs.java
xtraplatform-features-gml/src/main/java/de/ii/xtraplatform/features/gml/app/FilterEncoderWfs.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FeatureProviderSql.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureQueries.java

See commit comments for the changes.

Edits from pre-release tests

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FeatureProviderSqlFactory.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureSchema.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureSchemaTransformer.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/SchemaReferenceResolver.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/TypesResolver.java

Addresses interactive-instruments/ldproxy-project-management#159.

resolve schema recursively

---

xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/SqlHelper.java
xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/domain/MbtilesTileset.java

When testing CRUD operations, deleting tiles in MBTiles caches to trigger recreating tiles in updated areas resulted in SQLite errors ("database is locked"). These were the result of update statements inside `cleanupDuplicates()` inside a loop over a ResultSet with the tiles to process. Processing the tiles after closing the ResultSet resolved the errors.
The code has been updated to ensure ResultSets and Statements are closed, try-with is used for all statements. 
The PR also includes additional minor fixes and improvements.

fix MBTiles errors after CRUD operations

---

xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/Geometry.java
xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/Operand.java
xtraplatform-cql/src/test/groovy/de/ii/xtraplatform/cql/app/CqlJsonSpec.groovy
xtraplatform-cql/src/testFixtures/java/de/ii/xtraplatform/cql/app/CqlFilterExamples.java

- adds custom JSON deserializers for Point, MultiPoint, MultiLineString, and MultiPolygon
- adds custom JSON serializers for Point, MultiPoint, MultiLineString, MultiPolygon, and Envelope
- adds unit tests for all deserializers and serializers
Closes https://github.com/interactive-instruments/ldproxy/issues/1041.

fix CQL2-JSON geometry parsing errors

---

xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/SchemaDeriver.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/OnlyQueryables.java

Part of https://github.com/interactive-instruments/ldproxy/issues/1049

Support queryables in nested arrays

---

xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureStreamImpl.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureTokenTransformerCoordinates.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureTokenTransformerMappings.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeatureEventBuffer.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTokenSliceTransformer.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTransformerWrap.java
xtraplatform-features/src/test/groovy/de/ii/xtraplatform/features/domain/Util.groovy

This should fix the issues with `bergbau`.

fix implicit mappings

---

xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTokenSliceTransformer.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTransformerArrayReduceFormat.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTransformerConcat.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/PropertyTransformation.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/TokenSliceTransformerChain.java
xtraplatform-features/src/test/groovy/de/ii/xtraplatform/features/domain/TransformerSpec.groovy
xtraplatform-features/src/testFixtures/resources/feature-schemas/observation.yml
xtraplatform-features/src/testFixtures/resources/feature-tokens/observation.yml

I migrated the `sourcePaths` occurrences in `geoval` in branch `array-reduce`.

add transformer array reduce format

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/QuerySchemaDeriver.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/SqlQueryTemplatesDeriver.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlDialect.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlDialectGpkg.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlDialectPostGis.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureSchema.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/SchemaBase.java

Closes https://github.com/interactive-instruments/ldproxy/issues/1119

PostGIS: support geometry columns with curves

---

xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/SchemaConstraints.java

.. so far, they were available only in German

document schema constraints in English

---

xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureStreamImpl.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTransformerRename.java

Closes https://github.com/interactive-instruments/ldproxy/issues/1160

fix object rename

---

xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/ClusterAnalysis.java
xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/FeatureEncoderMVT.java
xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/SqlHelper.java
xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/TileCacheDynamic.java
xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/TileCacheImmutable.java
xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/TileProviderFeatures.java
xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/TileStoreMbTiles.java
xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/domain/MbtilesTileset.java
xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/domain/TileStore.java

See https://github.com/interactive-instruments/ldproxy/issues/1155.

Various seeding issues

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/ObjectSql.java
xtraplatform-geometries/src/main/java/de/ii/xtraplatform/geometries/domain/SimpleFeatureGeometry.java

Fixes interactive-instruments/ldproxy#1167.

fix type of inserted WKT geometries

---

xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureStreamImpl.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureTokenTransformerRemoveEmptyOptionals.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/PropertyTransformation.java
xtraplatform-features/src/test/groovy/de/ii/xtraplatform/features/domain/FeatureTokenTransformerRemoveEmptyOptionalsSpec.groovy

null values

---

xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/WithoutProperties.java

Closes https://github.com/interactive-instruments/ldproxy/issues/1207

Queries with fields: Reenable properties in objects

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/QuerySchemaDeriver.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/SqlQueryTemplatesDeriver.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/FeatureProviderSqlData.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SchemaSql.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlPath.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlPathParser.java

Closes interactive-instruments/ldproxy#1211.

support non-unique sort keys

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/JoinGenerator.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SchemaSql.java
xtraplatform-features-sql/src/test/groovy/de/ii/xtraplatform/features/sql/app/SqlQueryFixtures.groovy
xtraplatform-features-sql/src/test/groovy/de/ii/xtraplatform/features/sql/app/SqlQueryTemplatesDeriverSpec.groovy
xtraplatform-features-sql/src/test/resources/feature-schemas/okstra_abschnitt.yml
xtraplatform-features-sql/src/test/resources/sql-queries/okstra_abschnitt.yml
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/ImplicitMappingResolver.java

Closes https://github.com/interactive-instruments/ldproxy/issues/1193

fix join filters

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/FeatureProviderSqlData.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureQueriesExtension.java

Part of https://github.com/interactive-instruments/ldproxy/pull/1218

improve documentation

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/FeatureProviderSqlData.java

Update CQL2 document references. This is part of https://github.com/interactive-instruments/ldproxy/issues/1228.

upgrade FILTER maturity

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FeatureQueryEncoderSql.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/FeatureProviderSql.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureProvider.java

Part of https://github.com/interactive-instruments/ldproxy/issues/706

clean-up support for the result-type parameter

---

xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/SchemaDeriver.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/PropertyTransformation.java

part of https://github.com/interactive-instruments/ldproxy/issues/1238

add codelist identifiers for value properties

---

xtraplatform-feature-changes-sql/src/main/java/de/ii/xtraplatform/feature/changes/sql/app/FeatureChangesPgListener.java
xtraplatform-features-sql/src/test/groovy/de/ii/xtraplatform/features/sql/app/QuerySchemaFixtures.groovy
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureSchema.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/MappingOperationResolver.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/SchemaBase.java
xtraplatform-features/src/testFixtures/groovy/de/ii/xtraplatform/features/domain/FeatureSchemaFixtures.groovy
xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/TileGeneratorFeatures.java
xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/TileStoreMbTiles.java
xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/domain/TileGenerationSchema.java
xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/domain/VectorLayer.java

Note: this does not merge into `master`, but into `root-concat`.

additional root concatenation changes

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlQueryOptions.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/infra/db/SqlRowVals.java

Closes https://github.com/interactive-instruments/ldproxy/issues/1284

compute table schema only once

---

xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureSchema.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeatureRefResolver.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/OnlyQueryables.java
xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/OnlySortables.java

See https://github.com/interactive-instruments/ldproxy/issues/1288

add checks on queryable properties

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/infra/db/SqlClientRx.java

Closes https://github.com/interactive-instruments/ldproxy/issues/1293.

wrap SELECT/DELETE in transactions, too

---

xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FeatureQueryEncoderSql.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/SqlQueryTemplates.java
xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/SqlQueryTemplatesDeriver.java
xtraplatform-features-sql/src/test/groovy/de/ii/xtraplatform/features/sql/app/SqlQueryTemplatesDeriverSpec.groovy

Closes https://github.com/ldproxy/ldproxy/issues/1468

add override to force numberMatched
