ldproxy/xtraplatform-spatial

- xtraplatform-crs/src/main/java/de/ii/xtraplatform/crs/infra/GeoToolsCrsTransformerFactory.java
FME uses the code 900914 instead of 4979
> add workaround for EPSG 4979

- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/TemporalLiteral.java
- xtraplatform-cql/src/test/groovy/de/ii/xtraplatform/cql/app/CqlJsonSpec.groovy
- xtraplatform-cql/src/test/groovy/de/ii/xtraplatform/cql/app/CqlTextSpec.groovy
- xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/app/FilterEncoderSqlNewNewImpl.java
* If the `datetime` parameter uses dates, not timestamps, an interval that starts on the first second of the start date and ends at the last second of the end date is used.
* ISO 8601 intervals include both the start and end instant. PostgreSQL intervals are exclusive of the end instant, so we have to add one second to each end instant before creating the SQL interval.
> Updates to temporal filtering

- build.gradle
- xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/app/FilterEncoderSqlNewNewImpl.java
closes interactive-instruments/ldproxy#447
Note that the current code is not robust with respect to envelopes in other CRSs that are not the default CRSs. We should be able to get the necessary information from the CRS (what is the max and min longitude/easting value?), but this requires a more complex change to how we deal with CRSs. Perhaps this could be addressed as part of interactive-instruments/ldproxy#439.
> Support envelopes that span the anti-meridian

- xtraplatform-feature-provider-wfs/src/main/java/de/ii/xtraplatform/feature/provider/wfs/GMLSchemaParser.java
- xtraplatform-feature-provider-wfs/src/main/java/de/ii/xtraplatform/feature/provider/wfs/infra/WfsSchemaAnalyzer.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureType.java
- avoid collisions with feature properties "id" (reserved for `@gml:id`); the property is now mapped to `_id_` to avoid the collision
- an empty (default) namespace prefix caused errors in the feature output
- integers were mapped to FLOAT, not INTEGER
closes https://github.com/interactive-instruments/ldproxy/issues/454
> Fixes to issues with WFS backends

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureProperty.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/SchemaBase.java
The role identifies the type name of the object/feature and can be used, for example, in the JSON-LD `@type` annotation.
> add schema role TYPE

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/SchemaBase.java
currently, the start of a primary interval is in typical cases mapped to primary instant
> fix primary temporal property detection

- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/CqlImpl.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/CqlTypeChecker.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/Type.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/Cql.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/infra/CqlIncompatibleTypes.java
- xtraplatform-cql/src/test/groovy/de/ii/xtraplatform/cql/app/CqlTypeCheckerSpec.groovy
The only missing type information is for the properties, which is derived from the feature schema. Since the CQL2 module has no dependency to the features module, the type information is passed as a string. In error messages, the known types from the schema definitions are used, not the types used internally in the CQL2 implementation.
> Add type checks for CQL2 expressions

- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/CqlTypeChecker.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/Type.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/CqlToText.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/infra/CqlIncompatibleTypes.java
- xtraplatform-cql/src/test/groovy/de/ii/xtraplatform/cql/app/CqlTypeCheckerSpec.groovy
- xtraplatform-cql/src/testFixtures/java/de/ii/xtraplatform/cql/app/CqlFilterExamples.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FilterEncoderSql.java
- xtraplatform-features-sql/src/test/groovy/de/ii/xtraplatform/features/sql/app/FilterEncoderSqlSpec.groovy
- xtraplatform-features-sql/src/test/groovy/de/ii/xtraplatform/features/sql/app/QuerySchemaFixtures.groovy
* use 'COALESCE' to map properties in intervals that are 'null' to +/- infinity
* prohibit mixing DATE and DATETIME in INTERVAL()
* treat DATE values as DATES and avoid casting to Instant
* fix issue in CQL Text writer with INTERVAL()
> CQL2: improve handling of temporal data types

- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/CqlCoordinateChecker.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/CqlTypeChecker.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/CqlVisitorBase.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/CqlVisitorCopy.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/CqlVisitorMapTemporalOperators.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/Accenti.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/BinaryTemporalOperation.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/Casei.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/CqlToText.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/CqlVisitor.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/Function.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/In.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/Interval.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/IsNull.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/Operand.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/Temporal.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/domain/TemporalLiteral.java
- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/infra/CqlTextVisitor.java
- xtraplatform-cql/src/test/groovy/de/ii/xtraplatform/cql/app/CqlJsonSpec.groovy
- xtraplatform-cql/src/testFixtures/java/de/ii/xtraplatform/cql/app/CqlFilterExamples.java
- xtraplatform-features-gml/src/main/java/de/ii/xtraplatform/features/gml/app/FilterEncoderWfs.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FilterEncoderSql.java
casei(), accenti() and interval()  are no longer functions in the CQL2 grammar, but they still were in the internal representation, which required special treatment, e.g., in the JSON serializer. They have been moved to separate node subtypes.
> update casei(), accenti() and interval()

- build.gradle
- xtraplatform-crs/src/test/groovy/de/ii/xtraplatform/crs/infra/CrsTransformerProjSpec.groovy
change tests to support also ARM processors which give slightly different floating point values compared to Intel processors; uses 1e-6 for meter values and 1e-11 for degrees.
> update crs tests

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureTokenTransformerLogger.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureTokenTransformerSchemaMappings.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureTokenTransformerSorting.java
- fixes a bug in the merged version of #135, sorting does not work correctly for nested objects
- fixes the path in `onFeatureStart` and `onFeatureEnd`
> Fix transformations

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureTokenTransformerSorting.java
If the provider schema contains links between features, these are often expressed as Link objects like this:
```yaml
property:
type: OBJECT
objectType: Link
properties:
title:
sourcePath: foreign_key
type: STRING
href:
sourcePath: foreign_key
type: STRING
transformations:
- stringFormat: '{{serviceUrl}}/collections/target/items/{{value}}'
```
I had cases where I would get the following in GML:
```xml
<property 
xlink:href="http://localhost:7080/rest/services/api/collections/target/items/1" 
xlink:href="http://localhost:7080/rest/services/api/collections/target/items/1"/>
```
and in GeoJSON:
```json
"property": {
"href": "http://localhost:7080/rest/services/api/collections/target/items/1"
}
```
The problem seems to be in `FeatureTokenTransformerSorting` where only the `path` is buffered, …
> handle properties with the same path

- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FeatureQueryEncoderSql.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlConnector.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlQueryOptions.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/AbstractFeatureProvider.java
see https://github.com/interactive-instruments/ldproxy/issues/706
This addresses the SQL providers only, not the WFS providers.
> reactivate hitsOnly for SQL providers

- xtraplatform-cql/src/main/java/de/ii/xtraplatform/cql/app/CqlVisitorMapEnvelopes.java
A ST_Intersects() with a bounding box / polygon that is a point or a horizontal/vertical line results in an empty results (since it is an invalid polygon). Reduce an envelope that is a point to a point and reduce an envelope that is a horizontal/vertical line to a line string.
Closes https://github.com/interactive-instruments/ldproxy/issues/709
> handle degenerate bbox

- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/SqlQueryTemplatesDeriver.java
- xtraplatform-features-sql/src/test/groovy/de/ii/xtraplatform/features/sql/app/SqlQueryTemplatesDeriverSpec.groovy
- xtraplatform-features-sql/src/test/groovy/de/ii/xtraplatform/features/sql/app/SqlQueryTemplatesFixtures.groovy
The stored query https://t18.ldproxy.net/d103_airports/search/surface-areas?type=PARKING&airports=JFK,EWR,LGA&offset=10&f=json matches 13 apronelement features, but more features were returned. The additional features were in GeoJSON `{"type": "Feature", "properties": null, "geometry": null}`.
The reason was the following value query for the join to apron. The following SQL query was generated:
`A.airport AS CSKEY_0, A.ogc_fid AS SKEY, B.ogc_fid AS SKEY_1, B.name, B.ogc_fid FROM apronelement A JOIN apron B ON (A.associatedapron=B.gml_id) WHERE (A.ogc_fid IN (SELECT AAA.ogc_fid FROM apronelement AAA WHERE ((AAA.ogc_fid IN (SELECT AA.ogc_fid FROM apronelement AA WHERE AA.aixmtype = 'PARKING') AND A.ogc_fid IN (SELECT AA.ogc_fid FROM apronelement AA WHERE AA.airport IN ('JFK','EWR','LGA')))) …
> fix issue with filter expression with logical operator in a join value query

- xtraplatform-features-gml/src/main/java/de/ii/xtraplatform/features/gml/app/FilterEncoderWfs.java
The datetime parameter is converted to a CQL2 expression with these operators. datetime was supported in the past and should continue to be supported.
> Support <= and >= for WFS providers

- xtraplatform-crs/src/main/java/de/ii/xtraplatform/crs/domain/CrsInfo.java
- xtraplatform-crs/src/main/java/de/ii/xtraplatform/crs/infra/CrsTransformerFactoryProj.java
Currently this is done in multiple places in ldproxy, but this depends on the CRS implementation and should be centralized in the CRS module.
> Centralize analysis of coordinate precision of CRS

- build.gradle
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FilterEncoderSql.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/QuerySchemaDeriver.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlDialect.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlDialectPostGis.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/SchemaBase.java
- introduces a schema-based detection for 3d geometries
- enables usage of different spatial operators for 3d geometries
- currently the only case is to use `ST_3DIntersects` for polyhedral surfaces (composite and closed MultiPolygon) with PostGIS
> sql spatial operators for 3d

- xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/TileGeneratorFeatures.java
If a tile provider from features currently includes layers that reference a non-existing feature provider, an exception is thrown that does not provide a hint how to fix the configuration. This change throws an error, if there is no feature type associated with a layer. If the feature type has no primary geometry, the layer will now exclude all features instead of throwing an error.
The configuration should be validated during provider startup.
> Tiles: Improve handling of configuration issues

- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FeatureProviderSqlFactory.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlDialect.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlDialectGpkg.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/infra/db/SchemaGeneratorSql.java
Closes https://github.com/interactive-instruments/ldproxy/issues/959
Tested with daraa.gpkg (EPSG:4326, requires LON_LAT enforcement) and Weinlagen.gpkg (EPSG:25832, already LON_LAT, or more correctly, Easting/Northing).
> GPKG: Enforce LON_LAT order in auto mode

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/WithScope.java
If ID properties are not included in the schema, CRUD operations will fail (even if the ID is not part of the payload). This includes DELETE, too.
> include ID properties in schemas in all scopes

- xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/FeatureEncoderMVT.java
- xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/TileGeometryUtil.java
- Improve tile geometry validity
- If a tile geometry is invalid, continue to try to fix it, but reduce the result again to the tile grid. Stop after two attempts.
- Small improvements 
- If determining a "full" tile fails, simply ignore the exception and assume false.
- Log the error message for invalid tile geometries.
> Tiles: Address comments/issues from the OGC June 2023 Code Sprint

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureStream.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureStreamImpl.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureTokenTransformerHasFeatures.java
`Result.isEmpty` is only true if there were no bytes written. But there might be bytes written even if the query did not result in any features. To detect this case, this adds `Result.hasFeatures`.
> add hasFeatures to FeatureStream.Result

- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FeatureProviderSql.java
Closes https://github.com/interactive-instruments/ldproxy/issues/1027
Tested with the daraa API:
```sh
curl -i -X POST "http://localhost:7080/rest/services/daraa/collections/CulturePnt/items" -H  "Content-Type: application/geo+json" -d "{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[36.0864929,32.6010818]},\"properties\":{\"F_CODE\":\"AL030\",\"ZI001_SDV\":\"2015-12-27T18:39:59Z\",\"UFI\":\"7ab54c93-b054-406f-9cf1-6921fd633277\",\"ZI005_FNA\":\"Test\",\"FCSUBTYPE\":100092,\"ZI037_REL\":11}}"
curl -i -X PUT "http://localhost:7080/rest/services/daraa/collections/CulturePnt/items/6" -H  "Content-Type: application/geo+json" -d "{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[36.1864929,32.7010818]},\"properties\":{\"F_CODE\":\"AL030\",\"ZI001_SD …
```
> set hasFeatures in mutation results

- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/ObjectSql.java
When creating the INSERT statements for a column with type FEATURE_REF, the value was not quoted. As a result, inserting the value 0-20000-0-60191 resulted in the value -80191 in the database. This change quotes also FEATURE_REF values of value type STRING.
Note: No issue is required since FEATURE_REF will only be introduced in v3.5.0.
> fix handling CRUD requests with FEATURE_REF properties

- xtraplatform-schemas-ext/build.gradle
closes https://github.com/interactive-instruments/ldproxy/issues/1068
This seems to fix the issue, but it would be good to understand why the old version stopped to work.
> upgrade  jsonschemafriend

- xtraplatform-schemas-ext/build.gradle
The version of Jsoup added in #228 introduced a CVE. This upgrades it to the most recent version.
> upgrade jsoup

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/OnlyQueryables.java
The queryables schema of a feature without a queryable is a schema without a property, not null. This was intended to be fixed by a commit in #233, but the fix was incorrect.
> fix for types without a queryable

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeatureRefResolver.java
Currently, only static feature references (fixed `refType`) are handled in `FeatureRefResolver`. There are, however, cases where dynamic feature references can be queryable, too. This is the case, if the type is determined by a `type` property that is not constant, but takes the `refType` value from a column. No concat/coalesce is used in this case.
> queryable dynamic feature references

- xtraplatform-schemas-ext/src/main/java/de/ii/xtraplatform/schemas/ext/app/LocalSchemaFragmentResolver.java
For some reason, `LocalSchemaFragmentResolver` is no longer found after the move from `schemas.ext` to `features` in #248. While the class belongs to features, I revert the move temporarily until the proper fix has been implemented.
> revert moving LocalSchemaFragmentResolver

- xtraplatform-features-gml/src/main/java/de/ii/xtraplatform/features/gml/domain/FeatureProviderWfsData.java
- xtraplatform-features-graphql/src/main/java/de/ii/xtraplatform/features/graphql/domain/FeatureProviderGraphQlData.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/FeatureProviderSqlData.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SchemaSql.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureProviderCommonData.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureSchema.java
Compute key data hashes that are often called several times per object only once. For entities, where `hashCode()` is called at several times, pre-compute the hash. For schema objects, compute the hash lazily.
> compute key data hashes once

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/app/FeatureChangeHandlerImpl.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureChangeHandler.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/ProviderData.java
When an API entity is reloaded or removed, the existing change listeners are still registered in the handler. They need to be removed on reload or shutdown.
> support removing change listeners

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTransformerObjectRemoveSelect.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/PropertyTransformation.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/TokenSliceTransformerChain.java
... in case the specified property is `null`.
Execute the transformer before the other slice transformers.
> add transformer to remove an object

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/WithoutProperties.java
If a FEATURE_REF property is included in a projection, the sub-properties of the FEATURE_REF object must be selected, too, not just the object-valued property.
Closes https://github.com/interactive-instruments/ldproxy/issues/1144.
> include feature ref properties in projection

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/SchemaMapping.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/SchemaToPathsVisitor.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTokenSliceTransformer.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTransformerCoalesce.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTransformerObjectReduceSelect.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTransformerObjectRemoveSelect.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeatureRefResolver.java
- xtraplatform-features/src/test/groovy/de/ii/xtraplatform/features/domain/TransformerSpec.groovy
- xtraplatform-features/src/testFixtures/resources/feature-schemas/pfs_plan-hatObjekt-coalesce.yml
- xtraplatform-features/src/testFixtures/resources/feature-schemas/pfs_plan-hatObjekt-value-coalesce.yml
- xtraplatform-features/src/testFixtures/resources/feature-tokens/pfs_plan-hatObjekt.yml
I think the original approach in `FeaturePropertyTransformerObjectRemoveSelect` was correct, the only bug was that it added the whole slice to the result and ignored start and end.
Apart from that there were some general issues in `FeaturePropertyTokenSliceTransformer` that also affected `objectReduceSelect`.
I also added some cases with `objectRemoveSelect` to the unit tests.
If this does not work you, I would need the specific use case.
> fix removeSelect and reduceSelect

- xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/TileEncoderMvt.java
- xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/TileStoreMbTiles.java
- xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/domain/MbtilesTileset.java
This is a follow-up to #260:
- In addition to failure when writing a tile during seeding, SQL errors when reading a tile during seeding are now also caught and only result in a log entry, but these do not stop the seeding thread.
- When writing a tile fails repeatedly, the message from the last failed attempt is written to the log.
> MBTiles Cache: Additional improvements

- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FeatureProviderSqlFactory.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/FeatureProviderSqlData.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureProviderDataV2.java
This change fixes two issues:
- The label template was only applied, if there was an explicit label that differs from the name. It is now always applied, using the name as the default label.
- The label template was not applied on properties in `fragments`. This is addressed by moving the schema transformation after resolving the schemas. So far the labelTemplate transformer was the only transformer applied in `FeatureProviderSqlData` while all the other transformers are applied in `FeatureProviderSqlFactory`.
In addition, after the schema resolver transformation has been applied, the fragments are no longer used and can be removed from the data.
This is an undocumented option. Shouldn't the option be documented?
Closes https://github.com/interactive-instruments/ldproxy/issues/1259
> fix labelTemplate

- xtraplatform-crs/src/main/java/de/ii/xtraplatform/crs/infra/CrsTransformerProj.java
- xtraplatform-geometries/src/main/java/de/ii/xtraplatform/geometries/domain/CoordinatesTransformer.java
For cases, where source and target CRS use a different unit, maxAllowableOffset was not applied correctly.
Example: the native CRS is metric and requested CRS is CRS84, e.g., the `strassen` API. A sample request is https://demo.ldproxy.net/strassen/collections/abschnitteaeste/items/3712041O3713038A?maxAllowableOffset=1, where the value should be treated as 1°, but 1m is applied.
> fix maxAllowableOffset

- xtraplatform-features-json/src/main/java/de/ii/xtraplatform/features/json/app/DecoderFactoryJson.java
- xtraplatform-features-oracle/src/main/java/de/ii/xtraplatform/features/oracle/app/FeatureProviderOracle.java
- xtraplatform-features-sql/build.gradle
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/DecoderFactorySqlExpression.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FeatureDecoderSql.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/JoinGenerator.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/QuerySchemaDeriver.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/SqlQueryTemplatesDeriver.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/FeatureProviderSql.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SchemaSql.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlDialect.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlDialectGpkg.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlDialectPgis.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlPath.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlPathParser.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/domain/SqlRelation.java
- xtraplatform-features-sql/src/test/groovy/de/ii/xtraplatform/features/sql/app/QuerySchemaDeriverSpec.groovy
- xtraplatform-features-sql/src/test/groovy/de/ii/xtraplatform/features/sql/app/SqlPathFixtures.groovy
- xtraplatform-features-sql/src/test/groovy/de/ii/xtraplatform/features/sql/app/SqlPathParserSpec.groovy
- xtraplatform-features-sql/src/test/groovy/de/ii/xtraplatform/features/sql/app/SqlQueryTemplatesDeriverSpec.groovy
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/app/DecoderFactoriesImpl.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/Decoder.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/DecoderFactories.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/DecoderFactory.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/SchemaMapping.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/OnlyQueryables.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/OnlySortables.java
Adds support for custom SQL expressions and other join types than `INNER`.
**Examples**
```yml
areaValue:
sourcePath: "[EXPRESSION]{sql=$T$.afl+55.5}"
type: FLOAT
```
```yml
geometrie:
sourcePath: "[sch=schl]katasterbezirk{joinType=LEFT}/geometrie"
```
**Todo**
> Advanced SQL

- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/infra/db/SqlClientRx.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/infra/db/SqlConnectorRx.java
The workaround introduced in #292 caused an issue with client aborts. This reverts the changes from #292 and implements a cleaner solution for the original issue that should not have any side effects.
> Issue 1293 again

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/profile/ProfileSet.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/profile/ProfileSetRel.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/profile/ProfileSetVal.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/profile/ProfileTransformations.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTransformerCodelist.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/FeaturePropertyTransformerValueType.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/SchemaTransformerChain.java
- xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/app/TileGeneratorFeatures.java
- xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/domain/TileGenerationOptions.java
- xtraplatform-tiles/src/main/java/de/ii/xtraplatform/tiles/domain/TilesetFeatures.java
Move the profiles and their associated property transformations to xtraplatform-features. All aspects related to API building block stays in ldproxy.
This PR also adds support for profiles in Vector Tiles generated from a feature provider. The profiles to be applied are declared in the tileset of a tile provider as an array with the key `profiles`. If declared in the tileset defaults, the profile will apply to all tilesets.
A new transformer was introduced to change the type of a codelist property (which may be an integer) to string to correctly represent the value type (otherwise the value is not encoded in the vector tile, because the actual type differs from the expected type).
Related to https://github.com/ldproxy/ldproxy/issues/1328.
> Move feature profiles to xtraplatform-features

- xtraplatform-features-oracle/src/main/java/de/ii/xtraplatform/features/oracle/app/FeatureProviderOracleFactory.java
- xtraplatform-features-sql/src/main/java/de/ii/xtraplatform/features/sql/app/FeatureProviderSqlFactory.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureSchema.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/DefaultRolesResolver.java
This pull request removes the checks in FeatureSchema that explicitly set PRIMARY_GEOMETRY, PRIMARY_INSTANT, PRIMARY_INTERVAL_START, and PRIMARY_INTERVAL_END roles.
Instead a new TypesResolver (DefaultRolesResolver) is executed as the final step during hydration of the SQL/Oracle providers. If no primary geometry is explicitly set, the first spatial property is assigned this role. If no primary instant or interval is explicitly set, the first temporal property is assigned this role.
Note that other roles including the primary interval start or end are only applied, if explicitly set in the provider schema.
Closes https://github.com/ldproxy/ldproxy/issues/1412
> Set default roles in new resolver

- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/FeatureSchema.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/SchemaBase.java
- xtraplatform-features/src/main/java/de/ii/xtraplatform/features/domain/transform/DefaultRolesResolver.java
@azahnen - While testing the issue with the order of the resolvers, I noticed an issue that was also introduced with the new DefaultRolesResolver in case of multiple levels of embedded features.
This commit includes two changes:
- The DefaultRolesResolver did not handle setting roles of embedded features;
- The methods to determine a property that has a role by default also included properties from embedded features, which is incorrect.
> fix embedding
